# Site settings
title: DIGITAL SERVICE at VA
# tagline: 
url: "https://department-of-veterans-affairs.github.io/dsva-portfolio"

# Social
# socialimg: /img/social.jpg # be sure to change this image
# facebook: fbusername
# twitter: twusername
# github: ghusername
# googleplus: gusername
# instagram: igusername

# Contact
# phone: 
# email: 

# Use this for production
#sass:
#    style: :compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
collections: 
 - team




